env:
  CIRRUS_CLONE_DEPTH: 1
  COVERITY_EMAIL: ENCRYPTED[b5c0701345dba2e40e6db6b16d3c6ecfdc1b4bc758e122b0d42931cad334bea4f13d3c3e91e776e04490420346bba757]
  COVERITY_SCAN_TOKEN: ENCRYPTED[c80d807eab99d4c4555d53725d89c69800312469e03c2c001dd3ae8c9b5b9db6464dd9da136f44676b461fe9e9d26f3a]

fetch_thirdparty: &fetch_thirdparty
  fetch_thirdparty_script:
    - mkdir -p thirdparty thirdparty/sqlite-amalgamation &&
      git clone --depth=1 https://github.com/c-ares/c-ares.git thirdparty/c-ares &&
      wget https://sqlite.org/2022/sqlite-amalgamation-3380500.zip -O thirdparty/sqlite-amalgamation.zip &&
      unzip -j thirdparty/sqlite-amalgamation.zip -d thirdparty/sqlite-amalgamation

cmake_build: &cmake_build
  env:
    BUILD_TYPE: "cmake"
  cmake_build_script:
    - cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DMSTDLIB_BUILD_FOR_CI=TRUE ${CMAKE_OPTS} -G Ninja -H. -B_builds &&
      cmake --build _builds

cmake_test: &cmake_test
  env:
    LD_LIBRARY_PATH: "$CIRRUS_WORKING_DIR/_builds/lib:$LD_LIBRARY_PATH"
    CTEST_OUTPUT_ON_FAILURE: "1"
    CK_VERBOSITY: "verbose"
  cmake_test_script:
    - cd _builds/test && ctest -VV && ifconfig && hostname && pwd && whoami

autotools_build: &autotools_build
  env:
    BUILD_TYPE: "autotools"
  autotools_build_script:
    - autoreconf -fi &&
      mkdir build &&
      cd build &&
      ../configure ${CONFIG_OPTS} &&
      ${MAKE} V=1 -j2

autotools_test: &autotools_test
  env:
    LD_LIBRARY_PATH: "$CIRRUS_WORKING_DIR/build/lib:$LD_LIBRARY_PATH"
    VERBOSE: "1"
    CK_VERBOSITY: "verbose"
  autotools_test_script:
    - cd build &&
      cp sql/sqlite/.libs/mstdlib_sql_sqlite.so sql/.libs/ &&
      make check

asan_build: &asan_build
  env:
    BUILD_TYPE: "asan"
    CC: "clang"
    CK_TIMEOUT_MULTIPLIER: "2"
  asan_deps_script:
    - |
      case "${CIRRUS_OS}" in
        linux)
          apt-get install -y clang clang-tools
          ;;
        freebsd)
          pkg install -y llvm
          ;;
        darwin)
          brew install llvm
          ;;
      esac
  asan_build_script:
    - cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DM_ASAN=TRUE -DMSTDLIB_BUILD_FOR_CI=TRUE ${CMAKE_OPTS} -G Ninja -H. -B_builds &&
      cmake --build _builds

static_analysis_build: &static_analysis_build
  env:
    BUILD_TYPE: "analyze"
    CC: "clang"
  static_analysis_deps_script:
    - |
      case "${CIRRUS_OS}" in
        linux)
          apt-get install -y clang clang-tools
          ;;
        freebsd)
          pkg install -y llvm
          ;;
        darwin)
          brew install llvm
          ;;
      esac
  static_analysis_build_script:
    - ${SCAN_BUILD} -v cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DMSTDLIB_BUILD_FOR_CI=TRUE ${CMAKE_OPTS} -G Ninja -H. -B_builds &&
      ${SCAN_BUILD} -v cmake --build _builds

valgrind_build: &valgrind_build
  env:
    BUILD_TYPE: "valgrind"
    CK_TIMEOUT_MULTIPLIER: "3"
  valgrind_deps_script:
    - |
      case "${CIRRUS_OS}" in
        linux)
          apt-get install -y valgrind
          ;;
        freebsd)
          pkg install -y valgrind
          ;;
        darwin)
          brew install valgrind
          ;;
      esac
  valgrind_build_script:
    - cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DMSTDLIB_USE_VALGRIND=ON -DMSTDLIB_BUILD_FOR_CI=TRUE ${CMAKE_OPTS} -G Ninja -H. -B_builds &&
      cmake --build _builds


coverity_install: &coverity_install
  env:
    COV_ARC: "$CIRRUS_WORKING_DIR/cov-analysis-$COV_PLATFORM.tgz"
    COV_DIR: "$CIRRUS_WORKING_DIR/coverity-scan-analysis"
    PATH: "$PATH:$CIRRUS_WORKING_DIR/cov-analysis/bin"
  coverity_install_script:
    - mkdir -p "${COV_DIR}"
    - curl -F project="Monetra/mstdlib"
           -F token="${COVERITY_SCAN_TOKEN}"
           -o "${COV_ARC}"
           "https://scan.coverity.com/download/cxx/${COV_PLATFORM}"
    - tar -zxpf "${COV_ARC}" -C "${COV_DIR}"
    - ln -s $(find "${COV_DIR}" -type d -name "cov-analysis*") cov-analysis

coverity_build: &coverity_build
  coverity_build_script:
    - cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DMSTDLIB_BUILD_FOR_CI=TRUE ${CMAKE_OPTS} -G Ninja .
    - cov-configure --comptype ${COV_COMPTYPE} --compiler ${CC} --template
    - cov-build --dir cov-int ninja

coverity_submit: &coverity_submit
  coverity_submit_script:
    - tar -czf analysis-results.tgz cov-int
    - curl -s -S -F project="Monetra/mstdlib"
                 -F token="${COVERITY_SCAN_TOKEN}"
                 -F file=@analysis-results.tgz
                 -F version="$(git rev-parse --short HEAD)"
                 -F description="Cirrus CI build"
                 -F email="${COVERITY_EMAIL}"
                 "https://scan.coverity.com/builds"


deploy_docs: &deploy_docs
  only_if: ${BRANCH} == 'master'
  deploy_docs_script:
    - ./gh-pages-deploy.sh


debian_template: &debian_template
  env:
    DIST: "DEBIAN"
    LC_ALL: "C"
    SCAN_BUILD: "scan-build"
    MAKE: "make"
    COV_COMPTYPE: gcc
    COV_PLATFORM: linux-x64
  osdeps_install_script:
    - apt-get update &&
      apt-get install -y cmake libssl-dev doxygen libpq-dev libmariadbd-dev unixodbc-dev libsqlite3-dev check ninja-build git wget curl unzip

debian_x64_template: &debian_x64_template
  << : *debian_template
  env:
    DIST: "DEBIAN"
    COV_PLATFORM: linux64

debian_arm64_template: &debian_arm64_template
  << : *debian_template
  env:
    DIST: "DEBIAN-ARM"

freebsd_template: &freebsd_template
  env:
    DIST: "FREEBSD"
    SCAN_BUILD: "scan-build"
    MAKE: "gmake"
  osdeps_install_script:
    - pkg install -y cmake check ninja mariadb-connector-c postgresql13-client unixODBC git wget unzip autoconf automake libtool gmake

macos_template: &macos_template
  env:
    DIST: "MACOS"
    SCAN_BUILD: "/opt/homebrew/opt/llvm/bin/scan-build"
    MAKE: "make"
    OPENSSL_ROOT_DIR: "/opt/homebrew/opt/openssl@3"
    PostgreSQL_DIR: "/opt/homebrew/opt/libpq"
    CONFIG_OPTS: "--with-openssl-dir=/opt/homebrew/opt/openssl@3 --with-sqlite-dir=/opt/homebrew/opt/sqlite3 --with-postgresql-dir=/opt/homebrew/opt/libpq --with-check-dir=/opt/homebrew/opt/check"
    CMAKE_OPTS: "-DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR -DPostgreSQL_DIR=$PostgreSQL_DIR"
  osdeps_install_script:
    - brew update &&
      brew install openssl doxygen mariadb-connector-c unixodbc libpq check ninja cmake git wget unzip autoconf automake libtool make

# ----- DEBIAN x64 -----

task:
  name: "Debian x64 - CMake"
  container:
    image: debian:latest
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *cmake_build
  << : *cmake_test
  << : *deploy_docs

task:
  name: "Debian x64 - AutoTools"
  container:
    image: debian:latest
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *autotools_build
  << : *autotools_test

task:
  name: "Debian x64 - ASAN"
  container:
    image: debian:latest
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *asan_build
  << : *cmake_test

task:
  name: "Debian x64 - Static Analysis"
  container:
    image: debian:latest
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *static_analysis_build

task:
  name: "Debian x64 - Valgrind"
  container:
    image: debian:latest
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *valgrind_build
  << : *cmake_test

task:
  name: "Debian x64 - coverity"
  only_if: $BRANCH == 'coverity_scan'
  container:
    image: debian:latest
  env:
    CC: "gcc"
  << : *debian_x64_template
  << : *fetch_thirdparty
  << : *coverity_install
  << : *coverity_build
  << : *coverity_submit


# ----- DEBIAN arm64 -----

task:
  name: "Debian arm64 - CMake"
  arm_container:
    image: debian:latest
  << : *debian_arm64_template
  << : *fetch_thirdparty
  << : *cmake_build
  << : *cmake_test

task:
  name: "Debian arm64 - AutoTools"
  arm_container:
    image: debian:latest
  << : *debian_arm64_template
  << : *fetch_thirdparty
  << : *autotools_build
  << : *autotools_test

# Unknown issue, ASAN just hangs
#task:
#  name: "Debian arm64 - ASAN"
#  arm_container:
#    image: debian:latest
#  << : *debian_arm64_template
#  << : *fetch_thirdparty
#  << : *asan_build
#  << : *cmake_test

task:
  name: "Debian arm64 - Static Analysis"
  arm_container:
    image: debian:latest
  << : *debian_arm64_template
  << : *fetch_thirdparty
  << : *static_analysis_build


# ----- FreeBSD x64 -----

task:
  name: "FreeBSD x64 - CMake"
  freebsd_instance:
    image_family: freebsd-13-0
  << : *freebsd_template
  << : *fetch_thirdparty
  << : *cmake_build
  << : *cmake_test

task:
  name: "FreeBSD x64 - AutoTools"
  freebsd_instance:
    image_family: freebsd-13-0
  << : *freebsd_template
  << : *fetch_thirdparty
  << : *autotools_build
  << : *autotools_test

task:
  name: "FreeBSD x64 - Static Analysis"
  freebsd_instance:
    image_family: freebsd-13-0
  << : *freebsd_template
  << : *fetch_thirdparty
  << : *static_analysis_build


# ----- MacOS -----

task:
  name: "MacOS - CMake"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1
  << : *macos_template
  << : *fetch_thirdparty
  << : *cmake_build
  << : *cmake_test

task:
  name: "MacOS - AutoTools"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1
  << : *macos_template
  << : *fetch_thirdparty
  << : *autotools_build
  << : *autotools_test

task:
  name: "MacOS - Static Analysis"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1
  << : *macos_template
  << : *fetch_thirdparty
  << : *static_analysis_build


