language: c

dist: trusty
sudo: false

cache: apt

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
      - sourceline: 'ppa:adrozdoff/cmake' # newer cmake
    packages: &default_packages
      - cmake
      - libssl-dev
      - doxygen
      - libpq-dev
      - libmariadbd-dev
      - unixodbc-dev
      - check

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      env: OPENSSL_ROOT_DIR="" BUILD_TYPE="RelWithDebInfo"
      compiler: clang
    - os: linux
      env: OPENSSL_ROOT_DIR="" BUILD_TYPE="RelWithDebInfo"
      compiler: gcc
    - os: osx
      env: OPENSSL_ROOT_DIR="/usr/local/opt/openssl" BUILD_TYPE="RelWithDebInfo"


install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl doxygen mariadb-connector-c libiodbc libpq check; fi


# Put in 3rd party sources and chain build
before_script:
   - wget http://sqlite.org/2017/sqlite-amalgamation-3200100.zip
   - unzip sqlite-amalgamation-3200100.zip
   - mv sqlite-amalgamation-3200100 thirdparty/sqlite-amalgamation
   - git clone https://github.com/c-ares/c-ares.git thirdparty/c-ares


script:
    - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" -H. -B_builds
    - cmake --build _builds 
    - cmake --build _builds --target check
