language: c
cache: apt
dist: trusty
addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:adrozdoff/cmake' # newer cmake
    packages: &default_packages
      - cmake
      - libssl-dev
      - doxygen


matrix:
  include:
    - os: linux
    - os: osx


install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install doxygen; fi

# Put in 3rd party sources and chain build
before_script:
   - cd thirdparty
   - wget http://sqlite.org/2017/sqlite-amalgamation-3200100.zip
   - unzip sqlite-amalgamation-3200100.zip
   - mv sqlite-amalgamation-3200100 sqlite-amalgamation
   - git clone https://github.com/c-ares/c-ares.git c-ares
   - cd ..


script:  
    - mkdir -p build
    - cd build
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..; fi 
    - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cmake ..; fi
    - make -j2 || exit
    - cd ..

