language: c
cache: apt
dist: trusty
addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:adrozdoff/cmake' # newer cmake
    packages: &default_packages
      - cmake

matrix:
  include:
    - os: linux

    - os: osx

script:  
    - mkdir -p build
    - cd build
    - cmake .. || exit
    - make -j2 || exit
    - cd ..

