image: Visual Studio 2015

# Github/Bitbucket only: get source code for one particular commit as zip archive, instead of git clone'ing.
shallow_clone: true

# Github/Bitbucket only: per-file commit filtering
skip_commits:
  files:
    - .gitignore
    - '**/*.md'
    - .travis.yml

# List of build configurations to test.
configuration:
  - RelWithDebInfo

# Note: You can set extra cmake args for a particular matrix entry with CMAKE_EXTRA_OPTIONS. For example:
#     CMAKE_EXTRA_OPTIONS: -DOPENSSL_ROOT_DIR=C:/OpenSSL-Win32
environment:
  matrix:
    # MSVC 2015, 32-bit x86
    - COMPILER: MSVC
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: x86
      OPENSSL_PATH: C:\OpenSSL-v111-Win32\

    # MSVC 2015, 64-bit x86
    - COMPILER: MSVC
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: x64
      OPENSSL_PATH: C:\OpenSSL-v111-Win64\


    # MinGW, 32-bit x86
    - COMPILER: MINGW
      OPENSSL_PATH: C:\OpenSSL-v111-Win32\
      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
#      PATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
#      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%

install:
  # Rename sh.exe as sh.exe in PATH interferes with MinGW.
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  # Download and extract ninja, add it to PATH.
  - mkdir C:\projects\ninja
  - cd C:\projects\ninja
  - appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip" -FileName ninja.zip
  - 7z x ninja.zip > nul
  - set PATH=C:\projects\ninja;%PATH%
  - ninja --version

before_build:
  # Setup build environment for the selected compiler (not all compilers need to do anything here).
  #  -- Visual Studio --
  - if "%COMPILER%" == "MSVC" call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%

build_script:
  # Make build-mstdlib directory. Download c-ares, sqlite amalgamation and libcheck. Build and install libcheck.
  - mkdir C:\projects\build-mstdlib
  - cmake -DBUILDDIR=C:\projects\build-mstdlib -DCMAKE_BUILD_TYPE=%configuration% -P "%APPVEYOR_BUILD_FOLDER%\setup_thirdparty.cmake"
  # Build mstdlib.
  - cd C:\projects\build-mstdlib
  - cmake -GNinja
    -DCMAKE_BUILD_TYPE=%configuration%
    -DCMAKE_INSTALL_PREFIX=C:\projects\build-mstdlib\test_install
    -DMSTDLIB_BUILD_FOR_CI=TRUE
    -DOPENSSL_ROOT_DIR=%OPENSSL_PATH%
    %CMAKE_EXTRA_OPTIONS% %APPVEYOR_BUILD_FOLDER%
  - ninja install
 
# Add this line to cmake command to skip slow mstdlib tests (thread tests and check_event_timer)
#-DMSTDLIB_SKIP_SLOW_TESTS=TRUE

test_script:
  # Add a firewall exception to allow test programs to communicate on port 1234
  - netsh advfirewall firewall add rule name="Test Script Inbound Port 1234" dir=in action=allow protocol=TCP localport=1234
  - cd C:\projects\build-mstdlib\test
  - set CTEST_OUTPUT_ON_FAILURE=1
  - set CK_VERBOSITY=verbose
  - ps: ctest -VV | tee -FilePath "all_tests.log"
  
on_finish:
  - cd C:\projects\build-mstdlib\test
  - dir /B *.log > list.txt
  - cmake -E tar cfv all_tests.zip --format=zip --files-from=list.txt
  - appveyor PushArtifact all_tests.zip
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# Force build worker to stay open after build is done, so we can RDP into it.

# Enable RDP connections into build worker.
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

