os: Visual Studio 2015

environment:
  matrix:
#    - GENERATOR: "Visual Studio 14 2015"
#      CONFIG: RelWithDebInfo
#      OPENSSL_ROOT_DIR: "C:/OpenSSL-Win32"

#    - GENERATOR: "Visual Studio 14 2015 Win64"
#      CONFIG: RelWithDebInfo
#      OPENSSL_ROOT_DIR: "C:/OpenSSL-Win64"

    - GENERATOR: "MinGW Makefiles"
      CONFIG: RelWithDebInfo
      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%

install:
  - git clone https://github.com/c-ares/c-ares.git thirdparty/c-ares

build_script:
  - cmake "-G%GENERATOR%" "-DOPENSSL_ROOT_DIR=%OPENSSL_ROOT_DIR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
