#ifndef MSTDLIB_VERSION_H
#define MSTDLIB_VERSION_H

#define MSTDLIB_VERSION_MAJOR  1
#define MSTDLIB_VERSION_MINOR  0
#define MSTDLIB_VERSION_PATCH  0
#define MSTDLIB_VERSION_STRING "1.0.0"

#endif /* MSTDLIB_VERSION_H */
