.TH "include/mstdlib/formats Directory Reference" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mstdlib/formats Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBm_csv\&.h\fP"
.br
.ti -1c
.RI "file \fBm_ini\&.h\fP"
.br
.ti -1c
.RI "file \fBm_json\&.h\fP"
.br
.ti -1c
.RI "file \fBm_mtzfile\&.h\fP"
.br
.ti -1c
.RI "file \fBm_settings\&.h\fP"
.br
.ti -1c
.RI "file \fBm_verify\&.h\fP"
.br
.ti -1c
.RI "file \fBm_xml\&.h\fP"
.br
.in -1c
