.TH "m_cache" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_cache
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCache \- String/Void Pointer\fP"
.br
.ti -1c
.RI "\fBCache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cache (Hot) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
