.TH "m_datastructures" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_datastructures
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCache\fP"
.br
.ti -1c
.RI "\fBHashtable\fP"
.br
.ti -1c
.RI "\fBLists (Dynamic Arrays)\fP"
.br
.ti -1c
.RI "\fBLinked List\fP"
.br
.ti -1c
.RI "\fBQueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data Structures and Algorithms 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
