.TH "m_eventio_semipublic" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_eventio_semipublic
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBJava JNI helpers\fP"
.br
.ti -1c
.RI "\fBFunctions for creating and using custom I/O layers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interfaces that can be used when extending the I/O subsystem, requires manual inclusion of additional headers that are not in the normal public API\&.
.PP
These APIs are more likely to change from release to release and should not be considered as stable as the public interfaces\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
