.TH "m_eventio_base_addon" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_eventio_base_addon
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAddon for bandwidth shaping\fP"
.br
.ti -1c
.RI "\fBAddon for event and I/O tracing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common layers that stack on base IO objects 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
