.TH "m_eventio_base" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_eventio_base
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBBluetooth LE (Low Energy) IO functions\fP"
.br
.ti -1c
.RI "\fBBluetooth IO functions\fP"
.br
.ti -1c
.RI "\fBHID (Human Interface Device) IO functions\fP"
.br
.ti -1c
.RI "\fBLoopback (Simulation/Test) IO functions\fP"
.br
.ti -1c
.RI "\fBMade for iPod/iPhone/iPad IO functions\fP"
.br
.ti -1c
.RI "\fBNetwork I/O\fP"
.br
.ti -1c
.RI "\fBPIPE I/O functions\fP"
.br
.ti -1c
.RI "\fBSerial Port I/O functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some I/O layers are considered base layers and typically do not have any layers underneath them\&. These are subsystems that handle communication with an endpoint\&. While higher layers typically deal with manipulation of the data going into and out of the base end point layer\&. For example, Net is a base layer which handles sending and receiving data over a network socket\&. TLS is a layer above that manipulates (encrypts and decrypts) the data as it goes into and comes out of the Net layer\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
