.TH "m_formats" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_formats
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCSV\fP"
.br
.ti -1c
.RI "\fBINI\fP"
.br
.ti -1c
.RI "\fBJSON\fP"
.br
.ti -1c
.RI "\fBMstdlib TZ File\fP"
.br
.ti -1c
.RI "\fBSettings\fP"
.br
.ti -1c
.RI "\fBVerification\fP"
.br
.RI "Validation of strings against various standards (email address, domain name, etc\&.)\&. "
.ti -1c
.RI "\fBXML\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
#include <mstdlib/mstdlib_formats\&.h>

.fi
.PP
.PP
Data Formats 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
