.TH "m_hashtable" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_hashtable
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBHashtable \- Dictionary (string/string)\fP"
.br
.ti -1c
.RI "\fBHashtable \- Callback default implementations\fP"
.br
.ti -1c
.RI "\fBHashtable \- Multi\fP"
.br
.ti -1c
.RI "\fBHashtable \- String/Binary\fP"
.br
.ti -1c
.RI "\fBHashtable \- String/Index\fP"
.br
.ti -1c
.RI "\fBHashtable \- String/uint64\fP"
.br
.ti -1c
.RI "\fBHashtable \- String/Void Pointer\fP"
.br
.ti -1c
.RI "\fBHashtable \- uint64/Binary\fP"
.br
.ti -1c
.RI "\fBHashtable \- uint64/String\fP"
.br
.ti -1c
.RI "\fBHashtable \- uint64/uint64\fP"
.br
.ti -1c
.RI "\fBHashtable \- uint64/Void Pointer\fP"
.br
.ti -1c
.RI "\fBHashtable generic/base implementation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hashtable, meant for storing key/value pairs with O(1) insertion, deletion, and search time 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
