.TH "m_io_bwshaping" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_io_bwshaping
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBM_io_bwshaping_mode\fP \fBM_io_bwshaping_mode_t\fP"
.br
.ti -1c
.RI "typedef enum \fBM_io_bwshaping_direction\fP \fBM_io_bwshaping_direction_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBM_io_bwshaping_mode\fP { \fBM_IO_BWSHAPING_MODE_BURST\fP = 1, \fBM_IO_BWSHAPING_MODE_TRICKLE\fP = 2 }"
.br
.ti -1c
.RI "enum \fBM_io_bwshaping_direction\fP { \fBM_IO_BWSHAPING_DIRECTION_IN\fP = 1, \fBM_IO_BWSHAPING_DIRECTION_OUT\fP = 2 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBM_io_error_t\fP \fBM_io_add_bwshaping\fP (\fBM_io_t\fP *io, size_t *layer_id)"
.br
.ti -1c
.RI "M_bool \fBM_io_bwshaping_set_throttle\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 Bps)"
.br
.ti -1c
.RI "M_bool \fBM_io_bwshaping_set_throttle_mode\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, \fBM_io_bwshaping_mode_t\fP mode)"
.br
.ti -1c
.RI "M_bool \fBM_io_bwshaping_set_throttle_period\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 period_s, M_uint64 sample_frequency_ms)"
.br
.ti -1c
.RI "M_bool \fBM_io_bwshaping_set_latency\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 latency_ms)"
.br
.ti -1c
.RI "M_uint64 \fBM_io_bwshaping_get_Bps\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction)"
.br
.ti -1c
.RI "M_uint64 \fBM_io_bwshaping_get_totalbytes\fP (\fBM_io_t\fP *io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction)"
.br
.ti -1c
.RI "M_uint64 \fBM_io_bwshaping_get_totalms\fP (\fBM_io_t\fP *io, size_t layer_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Bandwidth Shaping Addon
.PP
Allows tracking and altering data flow though an io object\&.
.PP
Common uses:
.IP "\(bu" 2
Tracking bandwidth utilization\&.
.IP "\(bu" 2
Rate limiting download speed for connected clients\&.
.IP "\(bu" 2
Throttling to prevent network link saturation\&.
.IP "\(bu" 2
Testing real world network setups\&.
.IP "\(bu" 2
Determining how an application will preform in a bad environment\&. 
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBM_io_bwshaping_mode\fP \fBM_io_bwshaping_mode_t\fP"

.SS "typedef enum \fBM_io_bwshaping_direction\fP \fBM_io_bwshaping_direction_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBM_io_bwshaping_mode\fP"
Method of shaping\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIM_IO_BWSHAPING_MODE_BURST \fP\fP
Allow bursting of data for each throttle period 
.TP
\fB\fIM_IO_BWSHAPING_MODE_TRICKLE \fP\fP
Enforce data to be more evenly distributed across the throttle period 
.SS "enum \fBM_io_bwshaping_direction\fP"
Shaping direction\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIM_IO_BWSHAPING_DIRECTION_IN \fP\fP
.TP
\fB\fIM_IO_BWSHAPING_DIRECTION_OUT \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBM_io_error_t\fP M_io_add_bwshaping (\fBM_io_t\fP * io, size_t * layer_id)"
Add a BWShaping layer\&.
.PP
Adding a layer without any settings will track bandwidth utilization
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id this is added at\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SS "M_bool M_io_bwshaping_set_throttle (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 Bps)"
Throttle data by bytes per seconds\&.
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&. 
.br
\fIBps\fP Bytes per seconds that should be throttled\&. Bps = 0 is infinite\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SS "M_bool M_io_bwshaping_set_throttle_mode (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, \fBM_io_bwshaping_mode_t\fP mode)"
Set how the data throttling should function\&.
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&. 
.br
\fImode\fP Throttle mode\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SS "M_bool M_io_bwshaping_set_throttle_period (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 period_s, M_uint64 sample_frequency_ms)"
Set throttle period\&.
.PP
The period must be longer than the sample frequency\&. Meaning period * 1000 > sample frequency\&.
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&. 
.br
\fIperiod_s\fP Period in seconds\&. Must be at least 1\&. 
.br
\fIsample_frequency_ms\fP Frequency in milliseconds\&. Must be at least 15\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SS "M_bool M_io_bwshaping_set_latency (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction, M_uint64 latency_ms)"
Set latency\&.
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&. 
.br
\fIlatency_ms\fP Latency in milliseconds\&. 0 is no latency\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SS "M_uint64 M_io_bwshaping_get_Bps (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction)"
Get current Bps in period for direction
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Bps\&. 
.RE
.PP

.SS "M_uint64 M_io_bwshaping_get_totalbytes (\fBM_io_t\fP * io, size_t layer_id, \fBM_io_bwshaping_direction_t\fP direction)"
Get total number of bytes transferred for direction since beginning
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&. 
.br
\fIdirection\fP Direction this applies to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Count of bytes\&. 
.RE
.PP

.SS "M_uint64 M_io_bwshaping_get_totalms (\fBM_io_t\fP * io, size_t layer_id)"
Get total time of connection in ms
.PP
\fBParameters:\fP
.RS 4
\fIio\fP io object\&. 
.br
\fIlayer_id\fP Layer id to apply this to\&. This should be the same layer id returned form M_io_add_bwshaping\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Milliseconds\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
