.TH "m_io_pipe" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_io_pipe
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBM_io_error_t\fP \fBM_io_pipe_create\fP (\fBM_io_t\fP **reader, \fBM_io_t\fP **writer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pipe's are uni-directional connected endpoints, meaning one endpoint is a write-only endpoint, and the other endpoint is a read-only endpoint\&. Pipes are often used for inter-process communication\&. 
.SH "Function Documentation"
.PP 
.SS "\fBM_io_error_t\fP M_io_pipe_create (\fBM_io_t\fP ** reader, \fBM_io_t\fP ** writer)"
Create a pipe object
.PP
\fBParameters:\fP
.RS 4
\fIreader\fP io object for reading\&. 
.br
\fIwriter\fP io object for writing\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Result\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
