.TH "m_log_syslog" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_log_syslog
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBM_log_error_t\fP \fBM_log_module_add_syslog\fP (\fBM_log_t\fP *log, const char *product, \fBM_syslog_facility_t\fP facility, size_t max_queue_bytes, \fBM_log_module_t\fP **out_mod)"
.br
.ti -1c
.RI "\fBM_log_error_t\fP \fBM_log_module_syslog_set_tag_priority\fP (\fBM_log_t\fP *log, \fBM_log_module_t\fP *module, M_uint64 tags, \fBM_syslog_priority_t\fP priority)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to enable logging to a local syslog server\&.
.PP
Only available on some platforms\&.
.PP
Note: syslog messages are limited to 1024 chars / line\&. Lines longer than this will be truncated\&. 
.SH "Function Documentation"
.PP 
.SS "\fBM_log_error_t\fP M_log_module_add_syslog (\fBM_log_t\fP * log, const char * product, \fBM_syslog_facility_t\fP facility, size_t max_queue_bytes, \fBM_log_module_t\fP ** out_mod)"
Add a module to output to syslog (if supported by this platform)\&.
.PP
Note: syslog messages are limited to 1024 chars / line\&. Lines longer than this will be truncated\&.
.PP
If the library wasn't compiled with syslog support, this function will return \fBM_LOG_MODULE_UNSUPPORTED\fP when called, and no module will be added to the logger\&.
.PP
\fBParameters:\fP
.RS 4
\fIlog\fP logger object 
.br
\fIproduct\fP short tag string passed to syslog: if \fCNULL\fP, will be set to program name 
.br
\fIfacility\fP facility type to associate with all log messages, gets passed directly to syslog 
.br
\fImax_queue_bytes\fP max size of queue used to buffer asynchronous writes to syslog 
.br
\fIout_mod\fP handle for created module, or \fCNULL\fP if there was an error 
.RE
.PP
\fBReturns:\fP
.RS 4
error code 
.RE
.PP

.SS "\fBM_log_error_t\fP M_log_module_syslog_set_tag_priority (\fBM_log_t\fP * log, \fBM_log_module_t\fP * module, M_uint64 tags, \fBM_syslog_priority_t\fP priority)"
Associate the given user-defined tag(s) with a syslog priority\&.
.PP
If you don't associate a tag with a syslog priority, the default priority of \fBM_SYSLOG_INFO\fP will be used for that tag\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_LOG_ALL_TAGS\fP 
.PP
\fBM_log_all_tags_lt\fP 
.PP
\fBM_log_all_tags_lte\fP 
.PP
\fBM_log_all_tags_gt\fP 
.PP
\fBM_log_all_tags_gte\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIlog\fP logger object 
.br
\fImodule\fP handle of module to operate on 
.br
\fItags\fP user-defined power-of-two tag (or multiple power-of-two tags, OR'd together) 
.br
\fIpriority\fP single priority value to associate with the given tags 
.RE
.PP
\fBReturns:\fP
.RS 4
error code 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
