.TH "m_log_tag_ranges" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_log_tag_ranges
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_LOG_ALL_TAGS\fP   M_UINT64_MAX"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "M_uint64 \fBM_log_all_tags_lt\fP (M_uint64 tag)"
.br
.ti -1c
.RI "M_uint64 \fBM_log_all_tags_lte\fP (M_uint64 tag)"
.br
.ti -1c
.RI "M_uint64 \fBM_log_all_tags_gt\fP (M_uint64 tag)"
.br
.ti -1c
.RI "M_uint64 \fBM_log_all_tags_gte\fP (M_uint64 tag)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helpers for constructing ranges of power-of-two tags\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_LOG_ALL_TAGS   M_UINT64_MAX"
Convenience constant - when passed to a function that accepts multiple tags, indicates ALL tags should be used\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_log_all_tags_lt\fP 
.PP
\fBM_log_all_tags_lte\fP 
.PP
\fBM_log_all_tags_gt\fP 
.PP
\fBM_log_all_tags_gte\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "M_uint64 M_log_all_tags_lt (M_uint64 tag)"
Return all tags less than the given power-of-two tag, OR'd together\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_LOG_ALL_TAGS\fP 
.PP
\fBM_log_all_tags_lte\fP 
.PP
\fBM_log_all_tags_gt\fP 
.PP
\fBM_log_all_tags_gte\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fItag\fP single power-of-two tag value 
.RE
.PP
\fBReturns:\fP
.RS 4
all tags < given tag 
.RE
.PP

.SS "M_uint64 M_log_all_tags_lte (M_uint64 tag)"
Return all tags less than or equal to the given power-of-two tag, OR'd together\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_LOG_ALL_TAGS\fP 
.PP
\fBM_log_all_tags_lt\fP 
.PP
\fBM_log_all_tags_gt\fP 
.PP
\fBM_log_all_tags_gte\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fItag\fP single power-of-two tag value 
.RE
.PP
\fBReturns:\fP
.RS 4
all tags <= given tag 
.RE
.PP

.SS "M_uint64 M_log_all_tags_gt (M_uint64 tag)"
Return all tags greater than the given power-of-two tag, OR'd together\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_LOG_ALL_TAGS\fP 
.PP
\fBM_log_all_tags_lt\fP 
.PP
\fBM_log_all_tags_lte\fP 
.PP
\fBM_log_all_tags_gte\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fItag\fP single power of two tag value 
.RE
.PP
\fBReturns:\fP
.RS 4
all tags > given tag 
.RE
.PP

.SS "M_uint64 M_log_all_tags_gte (M_uint64 tag)"
Return all tags greater than or equal to the given power-of-two tag, OR'd together\&.
.PP
\fBSee also:\fP
.RS 4
\fBM_LOG_ALL_TAGS\fP 
.PP
\fBM_log_all_tags_lt\fP 
.PP
\fBM_log_all_tags_lte\fP 
.PP
\fBM_log_all_tags_gt\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fItag\fP single power of two tag value 
.RE
.PP
\fBReturns:\fP
.RS 4
all tags >= given tag 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
