.TH "m_log_nslog" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_log_nslog
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBM_log_error_t\fP \fBM_log_module_add_nslog\fP (\fBM_log_t\fP *log, size_t max_queue_bytes, \fBM_log_module_t\fP **out_mod)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to enable logging to macOS/iOS logging subsytem (NSLog)\&.
.PP
Only available when building for Apple platforms\&. 
.SH "Function Documentation"
.PP 
.SS "\fBM_log_error_t\fP M_log_module_add_nslog (\fBM_log_t\fP * log, size_t max_queue_bytes, \fBM_log_module_t\fP ** out_mod)"
Add a module to output to macOS/iOS logging subsystem (if we're building for an Apple platform)\&.
.PP
If the library wasn't compiled for an Apple device, this function will return \fBM_LOG_MODULE_UNSUPPORTED\fP when called, and no module will be added to the logger\&.
.PP
\fBParameters:\fP
.RS 4
\fIlog\fP logger object 
.br
\fImax_queue_bytes\fP max size of queue used to buffer asynchronous writer to NSLog 
.br
\fIout_mod\fP handle for created module, or \fCNULL\fP if there was an error 
.RE
.PP
\fBReturns:\fP
.RS 4
error code 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
