.TH "m_sql_driver_mysql" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_sql_driver_mysql
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
MySQL/MariaDB Driver
.PP
Driver Name: mysql
.PP
Driver Connection String Options:
.IP "\(bu" 2
db: Required\&. Database Name\&.
.IP "\(bu" 2
socketpath: Conditional\&. If using Unix Domain Sockets to connect to MySQL, this is the path to the Unix Domain Socket\&. Use the keyword of 'search' to search for the socket based on standard known paths\&. Cannot be used with host\&.
.IP "\(bu" 2
host: Conditional\&. If using IP or SSL/TLS to connect to MySQL, this is the hostname or IP address of the server\&. If not using the default port of 3306, may append a ':port#' to the end of the host\&. For specifying multiple hosts in a pool, hosts should be comma delimited\&. Cannot be used with socketpath\&. 
.PP
.nf
host=10\&.40\&.30\&.2,10\&.50\&.30\&.2:13306  

.fi
.PP

.IP "\(bu" 2
ssl: Optional\&. Defaults to false, if true enables SSL/TLS to the server\&.
.IP "\(bu" 2
mysql_engine: Optional\&. Used during table creation, defaults to INNODB\&. The default data storage engine to use with mysql\&. Typically it is recommended to leave this at the default\&.
.IP "\(bu" 2
mysql_charset: Optional\&. Used during table creation, defaults to UTF8\&.
.IP "\(bu" 2
max_isolation: Optional\&. Sets the maximum isolation level used for transactions\&. This is used to overwrite requests for SERIALIZABLE isolation levels, useful with Galera-based clusters that do not truly support Serializable isolation\&. Should use 'SELECT \&.\&.\&. FOR UPDATE' type syntax for row locking\&. Available settings: 'REPEATABLE READ', READ COMMITTED" 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
