.TH "m_sql" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_sql
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDynamic Module Loading Subsystem\fP"
.br
.ti -1c
.RI "\fBSQL Drivers\fP"
.br
.ti -1c
.RI "\fBSQL Error handling functions\fP"
.br
.ti -1c
.RI "\fBSQL Connection Management\fP"
.br
.ti -1c
.RI "\fBSQL Helpers\fP"
.br
.ti -1c
.RI "\fBSQL Query Extension/Portability Helpers\fP"
.br
.ti -1c
.RI "\fBSQL Module/Driver\fP"
.br
.ti -1c
.RI "\fBSQL Report Generation\fP"
.br
.ti -1c
.RI "\fBSQL Statement Management\fP"
.br
.ti -1c
.RI "\fBSQL Table/Schema Management\fP"
.br
.ti -1c
.RI "\fBSQL Transaction Handling\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
#include <mstdlib/mstdlib_sql\&.h>

.fi
.PP
.PP
SQL abstraction layer
.PP
\fBWarning:\fP
.RS 4
these interfaces are experimental and may not be implemented or operate as expected\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
