.TH "m_string" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_string
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFormat String Functions\fP"
.br
.ti -1c
.RI "\fBString Checking/Validation\fP"
.br
.ti -1c
.RI "\fBString Manipulation (and Duplication)\fP"
.br
.ti -1c
.RI "\fBString Manipulation (in\-place)\fP"
.br
.ti -1c
.RI "\fBString Searching\fP"
.br
.ti -1c
.RI "\fBString Parsing and Joining\fP"
.br
.ti -1c
.RI "\fBString Conversion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
String Validation and Manipulation Functions 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
