.TH "m_thread_system" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_thread_system
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBM_thread_poll\fP (struct pollfd fds[], nfds_t nfds, int timeout)"
.br
.ti -1c
.RI "M_bool \fBM_thread_sigmask\fP (int how, const sigset_t *set, sigset_t *oldset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Low level threading functionality\&. These are only provided due to fundamental and irreconcilable differences that they cannot be provided in a platform agnostic manner\&. 
.SH "Function Documentation"
.PP 
.SS "int M_thread_poll (struct pollfd fds[], nfds_t nfds, int timeout)"
Monitor a file descriptor waiting for it to become ready for I/O operations\&.
.PP
\fBParameters:\fP
.RS 4
\fIfds\fP Array of FDs to monitor with monitoring flags 
.br
\fInfds\fP Number of file descriptors in array\&. 
.br
\fItimeout\fP How long to wait before giving up in ms\&. -1 = infinite
.RE
.PP
\fBReturns:\fP
.RS 4
The number of ready fds, 0 if timeout, -1 on error\&. 
.RE
.PP

.SS "M_bool M_thread_sigmask (int how, const sigset_t * set, sigset_t * oldset)"
Examine and change blocked signals\&.
.PP
\fBParameters:\fP
.RS 4
\fIhow\fP How to change signal behavior\&. Values are
.IP "\(bu" 2
SIG_BLOCK
.IP "\(bu" 2
SIG_UNBLOCK
.IP "\(bu" 2
SIG_SETMASK 
.PP
.br
\fIset\fP What signals to set using how\&. Optional, NULL if only getting current signals from oldset\&. 
.br
\fIoldset\fP Previous signal status\&. Optional, NULL if only setting signals\&.
.RE
.PP
\fBReturns:\fP
.RS 4
M_TRUE on success, otherwise M_FALSE\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
