.TH "m_time_parse" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_time_parse
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBM_time_t\fP \fBM_time_from_str\fP (const char *timestr, const \fBM_time_tz_t\fP *tz, M_bool default_end_of_day)"
.br
.ti -1c
.RI "char * \fBM_time_to_str\fP (const char *fmt, const M_time_localtm_t *tm)"
.br
.ti -1c
.RI "char * \fBM_time_parsefmt\fP (const char *s, const char *fmt, M_time_localtm_t *tm)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBM_time_t\fP M_time_from_str (const char * timestr, const \fBM_time_tz_t\fP * tz, M_bool default_end_of_day)"
Parse a time string\&.
.PP
Supports offsets and fixed formats\&.
.PP
Offsets:
.PP
.IP "\(bu" 2
Support 'now', '+/-N magnitude', where magnitude is:
.IP "  \(bu" 4
year, month, day, hour, min, sec
.IP "  \(bu" 4
where long names and plural are supported
.PP

.PP
.PP
Ex: +6 Months or -7 hours
.PP
Fixed:
.PP
.IP "\(bu" 2
%m/%d/%Y %H
.IP "\(bu" 2
%m/%d/%Y %H %P
.IP "\(bu" 2
%m/%d/%Y %H %p
.IP "\(bu" 2
%m/%d/%Y %I %P
.IP "\(bu" 2
%m/%d/%Y %I %p
.IP "\(bu" 2
%m/%d/%Y %H%M
.IP "\(bu" 2
%m/%d/%Y %H%M %P
.IP "\(bu" 2
%m/%d/%Y %H%M %p
.IP "\(bu" 2
%m/%d/%Y %I%M %P
.IP "\(bu" 2
%m/%d/%Y %I%M %p
.IP "\(bu" 2
%m/%d/%Y %H%M%S
.IP "\(bu" 2
%m/%d/%Y %H%M%S %P
.IP "\(bu" 2
%m/%d/%Y %H%M%S %p
.IP "\(bu" 2
%m/%d/%Y %H%M%S %z
.IP "\(bu" 2
%m/%d/%Y %I%M%S %P
.IP "\(bu" 2
%m/%d/%Y %I%M%S %p
.IP "\(bu" 2
%m/%d/%Y %H%M%S %z
.IP "\(bu" 2
%m/%d/%Y %H:%M
.IP "\(bu" 2
%m/%d/%Y %H:%M %P
.IP "\(bu" 2
%m/%d/%Y %H:%M %p
.IP "\(bu" 2
%m/%d/%Y %I:%M %P
.IP "\(bu" 2
%m/%d/%Y %I:%M %p
.IP "\(bu" 2
%m/%d/%Y %H:%M:%S
.IP "\(bu" 2
%m/%d/%Y %H:%M:%S %P
.IP "\(bu" 2
%m/%d/%Y %H:%M:%S %p
.IP "\(bu" 2
%m/%d/%Y %I:%M:%S %P
.IP "\(bu" 2
%m/%d/%Y %I:%M:%S %p
.IP "\(bu" 2
%m/%d/%Y %H:%M:%S %z
.IP "\(bu" 2
%m/%d/%Y %H-%M
.IP "\(bu" 2
%m/%d/%Y %H-%M %P
.IP "\(bu" 2
%m/%d/%Y %H-%M %p
.IP "\(bu" 2
%m/%d/%Y %I-%M %P
.IP "\(bu" 2
%m/%d/%Y %I-%M %p
.IP "\(bu" 2
%m/%d/%Y %H-%M-%S
.IP "\(bu" 2
%m/%d/%Y %H-%M-%S %P
.IP "\(bu" 2
%m/%d/%Y %H-%M-%S %p
.IP "\(bu" 2
%m/%d/%Y %I-%M-%S %P
.IP "\(bu" 2
%m/%d/%Y %I-%M-%S %p
.IP "\(bu" 2
%m/%d/%Y %H-%M-%S %z
.IP "\(bu" 2
%m/%d/%Y T %H
.IP "\(bu" 2
%m/%d/%Y T %H %P
.IP "\(bu" 2
%m/%d/%Y T %H %p
.IP "\(bu" 2
%m/%d/%Y T %I %P
.IP "\(bu" 2
%m/%d/%Y T %I %p
.IP "\(bu" 2
%m/%d/%Y T %H%M
.IP "\(bu" 2
%m/%d/%Y T %H%M %P
.IP "\(bu" 2
%m/%d/%Y T %H%M %p
.IP "\(bu" 2
%m/%d/%Y T %I%M %P
.IP "\(bu" 2
%m/%d/%Y T %I%M %p
.IP "\(bu" 2
%m/%d/%Y T %H%M%S
.IP "\(bu" 2
%m/%d/%Y T %H%M%S %P
.IP "\(bu" 2
%m/%d/%Y T %H%M%S %p
.IP "\(bu" 2
%m/%d/%Y T %I%M%S %P
.IP "\(bu" 2
%m/%d/%Y T %I%M%S %p
.IP "\(bu" 2
%m/%d/%Y T %H%M%S %z
.IP "\(bu" 2
%m/%d/%Y T %H:%M
.IP "\(bu" 2
%m/%d/%Y T %H:%M %P
.IP "\(bu" 2
%m/%d/%Y T %H:%M %p
.IP "\(bu" 2
%m/%d/%Y T %I:%M %P
.IP "\(bu" 2
%m/%d/%Y T %I:%M %p
.IP "\(bu" 2
%m/%d/%Y T %H:%M:%S
.IP "\(bu" 2
%m/%d/%Y T %H:%M:%S %P
.IP "\(bu" 2
%m/%d/%Y T %H:%M:%S %p
.IP "\(bu" 2
%m/%d/%Y T %I:%M:%S %P
.IP "\(bu" 2
%m/%d/%Y T %I:%M:%S %p
.IP "\(bu" 2
%m/%d/%Y T %H:%M:%S %z
.IP "\(bu" 2
%m/%d/%Y T %H-%M
.IP "\(bu" 2
%m/%d/%Y T %H-%M %P
.IP "\(bu" 2
%m/%d/%Y T %H-%M %p
.IP "\(bu" 2
%m/%d/%Y T %I-%M %P
.IP "\(bu" 2
%m/%d/%Y T %I-%M %p
.IP "\(bu" 2
%m/%d/%Y T %H-%M-%S
.IP "\(bu" 2
%m/%d/%Y T %H-%M-%S %P
.IP "\(bu" 2
%m/%d/%Y T %H-%M-%S %p
.IP "\(bu" 2
%m/%d/%Y T %I-%M-%S %P
.IP "\(bu" 2
%m/%d/%Y T %I-%M-%S %p
.IP "\(bu" 2
%m/%d/%Y T %H-%M-%S %z
.IP "\(bu" 2
%m-%d-%Y %H
.IP "\(bu" 2
%m-%d-%Y %H %P
.IP "\(bu" 2
%m-%d-%Y %H %p
.IP "\(bu" 2
%m-%d-%Y %I %P
.IP "\(bu" 2
%m-%d-%Y %I %p
.IP "\(bu" 2
%m-%d-%Y %H%M
.IP "\(bu" 2
%m-%d-%Y %H%M %P
.IP "\(bu" 2
%m-%d-%Y %H%M %p
.IP "\(bu" 2
%m-%d-%Y %I%M %P
.IP "\(bu" 2
%m-%d-%Y %I%M %p
.IP "\(bu" 2
%m-%d-%Y %H%M%S
.IP "\(bu" 2
%m-%d-%Y %H%M%S %P
.IP "\(bu" 2
%m-%d-%Y %H%M%S %p
.IP "\(bu" 2
%m-%d-%Y %I%M%S %P
.IP "\(bu" 2
%m-%d-%Y %I%M%S %p
.IP "\(bu" 2
%m-%d-%Y %H%M%S %z
.IP "\(bu" 2
%m-%d-%Y %H:%M
.IP "\(bu" 2
%m-%d-%Y %H:%M %P
.IP "\(bu" 2
%m-%d-%Y %H:%M %p
.IP "\(bu" 2
%m-%d-%Y %I:%M %P
.IP "\(bu" 2
%m-%d-%Y %I:%M %p
.IP "\(bu" 2
%m-%d-%Y %H:%M:%S
.IP "\(bu" 2
%m-%d-%Y %H:%M:%S %P
.IP "\(bu" 2
%m-%d-%Y %H:%M:%S %p
.IP "\(bu" 2
%m-%d-%Y %I:%M:%S %P
.IP "\(bu" 2
%m-%d-%Y %I:%M:%S %p
.IP "\(bu" 2
%m-%d-%Y %H:%M:%S %z
.IP "\(bu" 2
%m-%d-%Y %H-%M
.IP "\(bu" 2
%m-%d-%Y %H-%M %P
.IP "\(bu" 2
%m-%d-%Y %H-%M %p
.IP "\(bu" 2
%m-%d-%Y %I-%M %P
.IP "\(bu" 2
%m-%d-%Y %I-%M %p
.IP "\(bu" 2
%m-%d-%Y %H-%M-%S
.IP "\(bu" 2
%m-%d-%Y %H-%M-%S %P
.IP "\(bu" 2
%m-%d-%Y %H-%M-%S %p
.IP "\(bu" 2
%m-%d-%Y %I-%M-%S %P
.IP "\(bu" 2
%m-%d-%Y %I-%M-%S %p
.IP "\(bu" 2
%m-%d-%Y %H-%M-%S %z
.IP "\(bu" 2
%m-%d-%Y T %H
.IP "\(bu" 2
%m-%d-%Y T %H %P
.IP "\(bu" 2
%m-%d-%Y T %H %p
.IP "\(bu" 2
%m-%d-%Y T %I %P
.IP "\(bu" 2
%m-%d-%Y T %I %p
.IP "\(bu" 2
%m-%d-%Y T %H%M
.IP "\(bu" 2
%m-%d-%Y T %H%M %P
.IP "\(bu" 2
%m-%d-%Y T %H%M %p
.IP "\(bu" 2
%m-%d-%Y T %I%M %P
.IP "\(bu" 2
%m-%d-%Y T %I%M %p
.IP "\(bu" 2
%m-%d-%Y T %H%M%S
.IP "\(bu" 2
%m-%d-%Y T %H%M%S %P
.IP "\(bu" 2
%m-%d-%Y T %H%M%S %p
.IP "\(bu" 2
%m-%d-%Y T %H%M%S %z
.IP "\(bu" 2
%m-%d-%Y T %I%M%S %P
.IP "\(bu" 2
%m-%d-%Y T %I%M%S %p
.IP "\(bu" 2
%m-%d-%Y T %H:%M
.IP "\(bu" 2
%m-%d-%Y T %H:%M %P
.IP "\(bu" 2
%m-%d-%Y T %H:%M %p
.IP "\(bu" 2
%m-%d-%Y T %I:%M %P
.IP "\(bu" 2
%m-%d-%Y T %I:%M %p
.IP "\(bu" 2
%m-%d-%Y T %H:%M:%S
.IP "\(bu" 2
%m-%d-%Y T %H:%M:%S %P
.IP "\(bu" 2
%m-%d-%Y T %H:%M:%S %p
.IP "\(bu" 2
%m-%d-%Y T %I:%M:%S %P
.IP "\(bu" 2
%m-%d-%Y T %I:%M:%S %p
.IP "\(bu" 2
%m-%d-%Y T %H:%M:%S %z
.IP "\(bu" 2
%m-%d-%Y T %H-%M
.IP "\(bu" 2
%m-%d-%Y T %H-%M %P
.IP "\(bu" 2
%m-%d-%Y T %H-%M %p
.IP "\(bu" 2
%m-%d-%Y T %I-%M %P
.IP "\(bu" 2
%m-%d-%Y T %I-%M %p
.IP "\(bu" 2
%m-%d-%Y T %H-%M-%S
.IP "\(bu" 2
%m-%d-%Y T %H-%M-%S %P
.IP "\(bu" 2
%m-%d-%Y T %H-%M-%S %p
.IP "\(bu" 2
%m-%d-%Y T %I-%M-%S %P
.IP "\(bu" 2
%m-%d-%Y T %I-%M-%S %p
.IP "\(bu" 2
%m-%d-%Y T %H-%M-%S %z
.IP "\(bu" 2
%m/%d/%y %H
.IP "\(bu" 2
%m/%d/%y %H %P
.IP "\(bu" 2
%m/%d/%y %H %p
.IP "\(bu" 2
%m/%d/%y %I %P
.IP "\(bu" 2
%m/%d/%y %I %p
.IP "\(bu" 2
%m/%d/%y %H%M
.IP "\(bu" 2
%m/%d/%y %H%M %P
.IP "\(bu" 2
%m/%d/%y %H%M %p
.IP "\(bu" 2
%m/%d/%y %I%M %P
.IP "\(bu" 2
%m/%d/%y %I%M %p
.IP "\(bu" 2
%m/%d/%y %H%M%S
.IP "\(bu" 2
%m/%d/%y %H%M%S %P
.IP "\(bu" 2
%m/%d/%y %H%M%S %p
.IP "\(bu" 2
%m/%d/%y %I%M%S %P
.IP "\(bu" 2
%m/%d/%y %I%M%S %p
.IP "\(bu" 2
%m/%d/%y %H%M%S %z
.IP "\(bu" 2
%m/%d/%y %H:%M
.IP "\(bu" 2
%m/%d/%y %H:%M %P
.IP "\(bu" 2
%m/%d/%y %H:%M %p
.IP "\(bu" 2
%m/%d/%y %I:%M %P
.IP "\(bu" 2
%m/%d/%y %I:%M %p
.IP "\(bu" 2
%m/%d/%y %H:%M:%S
.IP "\(bu" 2
%m/%d/%y %H:%M:%S %P
.IP "\(bu" 2
%m/%d/%y %H:%M:%S %p
.IP "\(bu" 2
%m/%d/%y %I:%M:%S %P
.IP "\(bu" 2
%m/%d/%y %I:%M:%S %p
.IP "\(bu" 2
%m/%d/%y %H:%M:%S %z
.IP "\(bu" 2
%m/%d/%y %H-%M
.IP "\(bu" 2
%m/%d/%y %H-%M %P
.IP "\(bu" 2
%m/%d/%y %H-%M %p
.IP "\(bu" 2
%m/%d/%y %I-%M %P
.IP "\(bu" 2
%m/%d/%y %I-%M %p
.IP "\(bu" 2
%m/%d/%y %H-%M-%S
.IP "\(bu" 2
%m/%d/%y %H-%M-%S %P
.IP "\(bu" 2
%m/%d/%y %H-%M-%S %p
.IP "\(bu" 2
%m/%d/%y %I-%M-%S %P
.IP "\(bu" 2
%m/%d/%y %I-%M-%S %p
.IP "\(bu" 2
%m/%d/%y %H-%M-%S %z
.IP "\(bu" 2
%m/%d/%y T %H
.IP "\(bu" 2
%m/%d/%y T %H %P
.IP "\(bu" 2
%m/%d/%y T %H %p
.IP "\(bu" 2
%m/%d/%y T %I %P
.IP "\(bu" 2
%m/%d/%y T %I %p
.IP "\(bu" 2
%m/%d/%y T %H%M
.IP "\(bu" 2
%m/%d/%y T %H%M %P
.IP "\(bu" 2
%m/%d/%y T %H%M %p
.IP "\(bu" 2
%m/%d/%y T %I%M %P
.IP "\(bu" 2
%m/%d/%y T %I%M %p
.IP "\(bu" 2
%m/%d/%y T %H%M%S
.IP "\(bu" 2
%m/%d/%y T %H%M%S %P
.IP "\(bu" 2
%m/%d/%y T %H%M%S %p
.IP "\(bu" 2
%m/%d/%y T %I%M%S %P
.IP "\(bu" 2
%m/%d/%y T %I%M%S %p
.IP "\(bu" 2
%m/%d/%y T %H%M%S %z
.IP "\(bu" 2
%m/%d/%y T %H:%M
.IP "\(bu" 2
%m/%d/%y T %H:%M %P
.IP "\(bu" 2
%m/%d/%y T %H:%M %p
.IP "\(bu" 2
%m/%d/%y T %I:%M %P
.IP "\(bu" 2
%m/%d/%y T %I:%M %p
.IP "\(bu" 2
%m/%d/%y T %H:%M:%S
.IP "\(bu" 2
%m/%d/%y T %H:%M:%S %P
.IP "\(bu" 2
%m/%d/%y T %H:%M:%S %p
.IP "\(bu" 2
%m/%d/%y T %I:%M:%S %P
.IP "\(bu" 2
%m/%d/%y T %I:%M:%S %p
.IP "\(bu" 2
%m/%d/%y T %H:%M:%S %z
.IP "\(bu" 2
%m/%d/%y T %H-%M
.IP "\(bu" 2
%m/%d/%y T %H-%M %P
.IP "\(bu" 2
%m/%d/%y T %H-%M %p
.IP "\(bu" 2
%m/%d/%y T %I-%M %P
.IP "\(bu" 2
%m/%d/%y T %I-%M %p
.IP "\(bu" 2
%m/%d/%y T %H-%M-%S
.IP "\(bu" 2
%m/%d/%y T %H-%M-%S %P
.IP "\(bu" 2
%m/%d/%y T %H-%M-%S %p
.IP "\(bu" 2
%m/%d/%y T %I-%M-%S %P
.IP "\(bu" 2
%m/%d/%y T %I-%M-%S %p
.IP "\(bu" 2
%m/%d/%y T %H-%M-%S %z
.IP "\(bu" 2
%Y/%m/%d %H
.IP "\(bu" 2
%Y/%m/%d %H %P
.IP "\(bu" 2
%Y/%m/%d %H %p
.IP "\(bu" 2
%Y/%m/%d %I %P
.IP "\(bu" 2
%Y/%m/%d %I %p
.IP "\(bu" 2
%Y/%m/%d %H%M
.IP "\(bu" 2
%Y/%m/%d %H%M %P
.IP "\(bu" 2
%Y/%m/%d %H%M %p
.IP "\(bu" 2
%Y/%m/%d %I%M %P
.IP "\(bu" 2
%Y/%m/%d %I%M %p
.IP "\(bu" 2
%Y/%m/%d %H%M%S
.IP "\(bu" 2
%Y/%m/%d %H%M%S %P
.IP "\(bu" 2
%Y/%m/%d %H%M%S %p
.IP "\(bu" 2
%Y/%m/%d %I%M%S %P
.IP "\(bu" 2
%Y/%m/%d %I%M%S %p
.IP "\(bu" 2
%Y/%m/%d %H%M%S %z
.IP "\(bu" 2
%Y/%m/%d %H:%M
.IP "\(bu" 2
%Y/%m/%d %H:%M %P
.IP "\(bu" 2
%Y/%m/%d %H:%M %p
.IP "\(bu" 2
%Y/%m/%d %I:%M %P
.IP "\(bu" 2
%Y/%m/%d %I:%M %p
.IP "\(bu" 2
%Y/%m/%d %H:%M:%S
.IP "\(bu" 2
%Y/%m/%d %H:%M:%S %P
.IP "\(bu" 2
%Y/%m/%d %H:%M:%S %p
.IP "\(bu" 2
%Y/%m/%d %I:%M:%S %P
.IP "\(bu" 2
%Y/%m/%d %I:%M:%S %p
.IP "\(bu" 2
%Y/%m/%d %H:%M:%S %z
.IP "\(bu" 2
%Y/%m/%d %H-%M
.IP "\(bu" 2
%Y/%m/%d %H-%M %P
.IP "\(bu" 2
%Y/%m/%d %H-%M %p
.IP "\(bu" 2
%Y/%m/%d %I-%M %P
.IP "\(bu" 2
%Y/%m/%d %I-%M %p
.IP "\(bu" 2
%Y/%m/%d %H-%M-%S
.IP "\(bu" 2
%Y/%m/%d %H-%M-%S %P
.IP "\(bu" 2
%Y/%m/%d %H-%M-%S %p
.IP "\(bu" 2
%Y/%m/%d %I-%M-%S %P
.IP "\(bu" 2
%Y/%m/%d %I-%M-%S %p
.IP "\(bu" 2
%Y/%m/%d %H-%M-%S %z
.IP "\(bu" 2
%Y/%m/%d T %H
.IP "\(bu" 2
%Y/%m/%d T %H %P
.IP "\(bu" 2
%Y/%m/%d T %H %p
.IP "\(bu" 2
%Y/%m/%d T %I %P
.IP "\(bu" 2
%Y/%m/%d T %I %p
.IP "\(bu" 2
%Y/%m/%d T %H%M
.IP "\(bu" 2
%Y/%m/%d T %H%M %P
.IP "\(bu" 2
%Y/%m/%d T %H%M %p
.IP "\(bu" 2
%Y/%m/%d T %I%M %P
.IP "\(bu" 2
%Y/%m/%d T %I%M %p
.IP "\(bu" 2
%Y/%m/%d T %H%M%S
.IP "\(bu" 2
%Y/%m/%d T %H%M%S %P
.IP "\(bu" 2
%Y/%m/%d T %H%M%S %p
.IP "\(bu" 2
%Y/%m/%d T %I%M%S %P
.IP "\(bu" 2
%Y/%m/%d T %I%M%S %p
.IP "\(bu" 2
%Y/%m/%d T %H%M%S %z
.IP "\(bu" 2
%Y/%m/%d T %H:%M
.IP "\(bu" 2
%Y/%m/%d T %H:%M %P
.IP "\(bu" 2
%Y/%m/%d T %H:%M %p
.IP "\(bu" 2
%Y/%m/%d T %I:%M %P
.IP "\(bu" 2
%Y/%m/%d T %I:%M %p
.IP "\(bu" 2
%Y/%m/%d T %H:%M:%S
.IP "\(bu" 2
%Y/%m/%d T %H:%M:%S %P
.IP "\(bu" 2
%Y/%m/%d T %H:%M:%S %p
.IP "\(bu" 2
%Y/%m/%d T %I:%M:%S %P
.IP "\(bu" 2
%Y/%m/%d T %I:%M:%S %p
.IP "\(bu" 2
%Y/%m/%d T %H:%M:%S %z
.IP "\(bu" 2
%Y/%m/%d T %H-%M
.IP "\(bu" 2
%Y/%m/%d T %H-%M %P
.IP "\(bu" 2
%Y/%m/%d T %H-%M %p
.IP "\(bu" 2
%Y/%m/%d T %I-%M %P
.IP "\(bu" 2
%Y/%m/%d T %I-%M %p
.IP "\(bu" 2
%Y/%m/%d T %H-%M-%S
.IP "\(bu" 2
%Y/%m/%d T %H-%M-%S %P
.IP "\(bu" 2
%Y/%m/%d T %H-%M-%S %p
.IP "\(bu" 2
%Y/%m/%d T %I-%M-%S %P
.IP "\(bu" 2
%Y/%m/%d T %I-%M-%S %p
.IP "\(bu" 2
%Y/%m/%d T %H-%M-%S %z
.IP "\(bu" 2
%Y-%m-%d %H
.IP "\(bu" 2
%Y-%m-%d %H %P
.IP "\(bu" 2
%Y-%m-%d %H %p
.IP "\(bu" 2
%Y-%m-%d %I %P
.IP "\(bu" 2
%Y-%m-%d %I %p
.IP "\(bu" 2
%Y-%m-%d %H%M
.IP "\(bu" 2
%Y-%m-%d %H%M %P
.IP "\(bu" 2
%Y-%m-%d %H%M %p
.IP "\(bu" 2
%Y-%m-%d %I%M %P
.IP "\(bu" 2
%Y-%m-%d %I%M %p
.IP "\(bu" 2
%Y-%m-%d %H%M%S
.IP "\(bu" 2
%Y-%m-%d %H%M%S %P
.IP "\(bu" 2
%Y-%m-%d %H%M%S %p
.IP "\(bu" 2
%Y-%m-%d %I%M%S %P
.IP "\(bu" 2
%Y-%m-%d %I%M%S %p
.IP "\(bu" 2
%Y-%m-%d %H%M%S %z
.IP "\(bu" 2
%Y-%m-%d %H:%M
.IP "\(bu" 2
%Y-%m-%d %H:%M %P
.IP "\(bu" 2
%Y-%m-%d %H:%M %p
.IP "\(bu" 2
%Y-%m-%d %I:%M %P
.IP "\(bu" 2
%Y-%m-%d %I:%M %p
.IP "\(bu" 2
%Y-%m-%d %H:%M:%S
.IP "\(bu" 2
%Y-%m-%d %H:%M:%S %P
.IP "\(bu" 2
%Y-%m-%d %H:%M:%S %p
.IP "\(bu" 2
%Y-%m-%d %I:%M:%S %P
.IP "\(bu" 2
%Y-%m-%d %I:%M:%S %p
.IP "\(bu" 2
%Y-%m-%d %H:%M:%S %z
.IP "\(bu" 2
%Y-%m-%d %H-%M
.IP "\(bu" 2
%Y-%m-%d %H-%M %P
.IP "\(bu" 2
%Y-%m-%d %H-%M %p
.IP "\(bu" 2
%Y-%m-%d %I-%M %P
.IP "\(bu" 2
%Y-%m-%d %I-%M %p
.IP "\(bu" 2
%Y-%m-%d %H-%M-%S
.IP "\(bu" 2
%Y-%m-%d %H-%M-%S %P
.IP "\(bu" 2
%Y-%m-%d %H-%M-%S %p
.IP "\(bu" 2
%Y-%m-%d %I-%M-%S %P
.IP "\(bu" 2
%Y-%m-%d %I-%M-%S %p
.IP "\(bu" 2
%Y-%m-%d %H-%M-%S %z
.IP "\(bu" 2
%Y-%m-%d T %H
.IP "\(bu" 2
%Y-%m-%d T %H %P
.IP "\(bu" 2
%Y-%m-%d T %H %p
.IP "\(bu" 2
%Y-%m-%d T %I %P
.IP "\(bu" 2
%Y-%m-%d T %I %p
.IP "\(bu" 2
%Y-%m-%d T %H%M
.IP "\(bu" 2
%Y-%m-%d T %H%M %P
.IP "\(bu" 2
%Y-%m-%d T %H%M %p
.IP "\(bu" 2
%Y-%m-%d T %I%M %P
.IP "\(bu" 2
%Y-%m-%d T %I%M %p
.IP "\(bu" 2
%Y-%m-%d T %H%M%S
.IP "\(bu" 2
%Y-%m-%d T %H%M%S %P
.IP "\(bu" 2
%Y-%m-%d T %H%M%S %p
.IP "\(bu" 2
%Y-%m-%d T %I%M%S %P
.IP "\(bu" 2
%Y-%m-%d T %I%M%S %p
.IP "\(bu" 2
%Y-%m-%d T %H%M%S %z
.IP "\(bu" 2
%Y-%m-%d T %H:%M
.IP "\(bu" 2
%Y-%m-%d T %H:%M %P
.IP "\(bu" 2
%Y-%m-%d T %H:%M %p
.IP "\(bu" 2
%Y-%m-%d T %I:%M %P
.IP "\(bu" 2
%Y-%m-%d T %I:%M %p
.IP "\(bu" 2
%Y-%m-%d T %H:%M:%S
.IP "\(bu" 2
%Y-%m-%d T %H:%M:%S %P
.IP "\(bu" 2
%Y-%m-%d T %H:%M:%S %p
.IP "\(bu" 2
%Y-%m-%d T %I:%M:%S %P
.IP "\(bu" 2
%Y-%m-%d T %I:%M:%S %p
.IP "\(bu" 2
%Y-%m-%d T %H:%M:%S %z
.IP "\(bu" 2
%Y-%m-%d T %H-%M
.IP "\(bu" 2
%Y-%m-%d T %H-%M %P
.IP "\(bu" 2
%Y-%m-%d T %H-%M %p
.IP "\(bu" 2
%Y-%m-%d T %I-%M %P
.IP "\(bu" 2
%Y-%m-%d T %I-%M %p
.IP "\(bu" 2
%Y-%m-%d T %H-%M-%S
.IP "\(bu" 2
%Y-%m-%d T %H-%M-%S %P
.IP "\(bu" 2
%Y-%m-%d T %H-%M-%S %p
.IP "\(bu" 2
%Y-%m-%d T %I-%M-%S %P
.IP "\(bu" 2
%Y-%m-%d T %I-%M-%S %p
.IP "\(bu" 2
%Y-%m-%d T %H-%M-%S %z
.IP "\(bu" 2
%m/%d/%Y
.IP "\(bu" 2
%m-%d-%Y
.IP "\(bu" 2
%m-%d-%y
.IP "\(bu" 2
%m/%d/%y
.IP "\(bu" 2
%m%d%Y
.IP "\(bu" 2
%m%d%y
.IP "\(bu" 2
%Y/%m/%d
.IP "\(bu" 2
%Y-%m-%d
.PP
.PP
\fBParameters:\fP
.RS 4
\fItimestr\fP The time string to parse\&. 
.br
\fIdefault_end_of_day\fP M_TRUE when the returned time be at the end of the day\&. 
.br
\fItz\fP The time zone to use\&. If NULL the local system time zone will be used\&. This will only be used if the parsed time does not include a fixed time zone offset\&.
.RE
.PP
\fBReturns:\fP
.RS 4
M_time_t of the parsed time\&. -1 on error\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBM_time_parsefmt\fP 
.RE
.PP

.SS "char* M_time_to_str (const char * fmt, const M_time_localtm_t * tm)"
Format a date and time as a string\&.
.PP
\fBParameters:\fP
.RS 4
\fIfmt\fP The format of the string\&. 
.br
\fItm\fP The tm strcut to read from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
NULL if failed to format string\&. Otherwise returns a NULL terminated string\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBM_time_parsefmt\fP 
.RE
.PP

.SS "char* M_time_parsefmt (const char * s, const char * fmt, M_time_localtm_t * tm)"
Parse a formatted time string into a tm structure\&.
.PP
Supports the following input descriptors:
.PP
.IP "\(bu" 2
%% - The % character\&.
.IP "\(bu" 2
%m - month in 2 digit format\&.
.IP "\(bu" 2
%d - day in 2 digit format\&.
.IP "\(bu" 2
%y - year in 2 digit format\&.
.IP "\(bu" 2
%Y - year in 4 digit format\&.
.IP "\(bu" 2
%H - hour in 2 digit (24 hour) format\&.
.IP "\(bu" 2
%I - hour in 2 digit (12 hour) format\&. Should be paired with am/pm descriptors\&.
.IP "\(bu" 2
%M - minutes in 2 digit format\&.
.IP "\(bu" 2
%S - seconds in 2 digit format\&.
.IP "\(bu" 2
%z - offset from gmt\&. RFC-822 Character(s) identifier or ISO 8601 [+-]hh[[:]mm] numeric offset\&.
.IP "\(bu" 2
%P, %p - AM/PM, am/pm (can parse A\&.M\&./P\&.M\&./a\&.m\&./p\&.m\&.)\&.
.PP
.PP
Notes on format:
.PP
.IP "\(bu" 2
Whitespace between descriptors is ignored but non-whitespace characters are not\&.
.IP "  \(bu" 4
E\&.G: '%m%d' is equivalent to '%m %d' but not equivalent to '%m 7 %d'\&.
.PP

.IP "\(bu" 2
YY is calculated as current year -80 to +20\&.
.IP "\(bu" 2
E\&.g\&. YY = 30\&. Current year is 2013\&. Parsed year will be 2030\&. YY = 50\&. Current year is 2013\&. Parsed year will be 1950\&.
.IP "\(bu" 2
z supports multiple representations of the zone information based on RFC-822 and ISO 8601:
.IP "  \(bu" 4
+/- Digit:
.IP "  \(bu" 4
[+-]hh[[:]mm] Named:
.IP "    \(bu" 6
UTC/GMT/UT/Z = 0
.IP "    \(bu" 6
EST/EDT = -5/-4
.IP "    \(bu" 6
CST/CDT = -6/-5
.IP "    \(bu" 6
MST/MDT = -7/-6
.IP "    \(bu" 6
PST/PDT = -8/-7 1ALPHA:
.IP "      \(bu" 8
A: -1 (J not used) to M: -12
.IP "      \(bu" 8
N: +1 to Y: +12
.PP

.PP

.PP

.PP
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The string to parse\&. 
.br
\fIfmt\fP The format of the string\&. 
.br
\fItm\fP The tm strcut to fill\&.
.RE
.PP
\fBReturns:\fP
.RS 4
NULL if failed to match format otherwise returns pointer to where it stopped processing in the buffer\&. If successfully processed entire buffer then returns pointer to NULL byte in buffer\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBM_time_from_str\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
