.TH "mstdlib_base" 3 "Tue Feb 20 2018" "Mstdlib-1.0.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mstdlib_base
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBString Functions\fP"
.br
.ti -1c
.RI "\fBData Structures/Algorithms\fP"
.br
.ti -1c
.RI "\fBBinary data\fP"
.br
.ti -1c
.RI "\fBBinary Conversion\fP"
.br
.ti -1c
.RI "\fBBitwise Buffered Data Builder\fP"
.br
.ti -1c
.RI "\fBBitwise Data Parser\fP"
.br
.ti -1c
.RI "\fBBuffered Data Builder\fP"
.br
.ti -1c
.RI "\fBCharacter\fP"
.br
.ti -1c
.RI "\fBDecimal\fP"
.br
.ti -1c
.RI "\fBEndian\fP"
.br
.ti -1c
.RI "\fBFile System\fP"
.br
.ti -1c
.RI "\fBgetopt\fP"
.br
.ti -1c
.RI "\fBMath\fP"
.br
.ti -1c
.RI "\fBMemory\fP"
.br
.ti -1c
.RI "\fBData Parser\fP"
.br
.ti -1c
.RI "\fBPseudo Random Number Generator (PRNG)\fP"
.br
.ti -1c
.RI "\fBSearch and Sort\fP"
.br
.ti -1c
.RI "\fBState Machine\fP"
.br
.ti -1c
.RI "\fBTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
#include <mstdlib/mstdlib\&.h>

.fi
.PP
.PP
Base punctuality such as data structures 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mstdlib-1\&.0\&.0 from the source code\&.
