#ifndef MSTDLIB_VERSION_H
#define MSTDLIB_VERSION_H

#define MSTDLIB_VERSION_MAJOR  @MSTDLIB_VERSION_MAJOR@
#define MSTDLIB_VERSION_MINOR  @MSTDLIB_VERSION_MINOR@
#define MSTDLIB_VERSION_PATCH  @MSTDLIB_VERSION_PATCH@
#define MSTDLIB_VERSION_STRING "@MSTDLIB_VERSION_STRING@"

#endif /* MSTDLIB_VERSION_H */
