/* #undef HAVE_IO_H */
#define HAVE_STRING_H
#define HAVE_STRINGS_H
#define HAVE_ERRNO_H
#define HAVE_UNISTD_H
#define HAVE_SYS_IOCTL_H
#define HAVE_SYS_SELECT_H
#define HAVE_SYS_TIME_H
#define HAVE_SYS_TYPES_H
#define HAVE_SYS_SOCKET_H
#define HAVE_SYS_UN_H
#define HAVE_NETINET_IN_H
#define HAVE_ARPA_INET_H
#define HAVE_NETDB_H
#define HAVE_NETINET_TCP_H
#define HAVE_VALGRIND_H
#define HAVE_STDDEF_H
#define HAVE_STDALIGN_H

#define HAVE_STRCASECMP
#define HAVE_STRNCASECMP
/* #undef HAVE__STRICMP */
/* #undef HAVE__STRNICMP */
/* #undef HAVE_SIGTIMEDWAIT */
#define HAVE_SIGWAIT
#define HAVE_LOCALTIME_R
#define HAVE_INET_PTON
#define HAVE_INET_NTOP
#define HAVE_GETCONTEXT
/* #undef HAVE_SECURE_GETENV */

#define HAVE_GETPWUID_5
/* #undef HAVE_GETPWUID_4 */

#define HAVE_GETGRGID_5
/* #undef HAVE_GETGRGID_4 */

#define HAVE_GETPWNAM_5
/* #undef HAVE_GETPWNAM_4 */

#define HAVE_GETGRNAM_5
/* #undef HAVE_GETGRNAM_4 */

#define HAVE_ST_BIRTHTIME

#define HAVE_READDIR_3
/* #undef HAVE_READDIR_2 */

#define HAVE_DIRENT_TYPE
#define STRUCT_TM_HAS_GMTOFF
#define STRUCT_TM_HAS_ZONE

#define HAVE_SOCKLEN_T
#define HAVE_SOCKADDR_STORAGE
#define HAVE_MAX_ALIGN_T
#define HAVE_ALIGNOF
/* #undef HAVE_ACCEPT4 */
/* #undef HAVE_PIPE2 */

/* #undef _FILE_OFFSET_BITS */
/* #undef _LARGE_FILES */
/* #undef _LARGE_FILE_SOURCE */

/* #undef HAVE_ATOMIC_H */
#define HAVE_PTHREAD
#define HAVE_PTHREAD_H
/* #undef HAVE_PTHREAD_INIT */
/* #undef HAVE_PTHREAD_YIELD */
#define HAVE_PTHREAD_RWLOCK_INIT
/* #undef HAVE_PTHREAD_RWLOCKATTR_SETKIND_NP */

/* #undef PTHREAD_SLEEP_USE_POLL */
#define PTHREAD_SLEEP_USE_SELECT
/* #undef PTHREAD_SLEEP_USE_NANOSLEEP */

#define HAVE_SYSCONF

#define HAVE_KQUEUE
/* #undef HAVE_EPOLL */
/* #undef HAVE_EPOLL_CREATE1 */

#define HAVE_DLFCN_H
#define HAVE_DLOPEN
/* #undef HAVE_LOADLIBRARY */

#define HAVE_VA_COPY
#define HAVE_VA___COPY
/* #undef VA_LIST_IS_ARRAY_TYPE */
#define VA_LIST_IS_POINTER_TYPE

#define MSTDLIB_INTERNAL
